INSERT INTO BLOG_POSTS (TITLE,BODY,DATE_ADDED,DATE_MODIFIED) 
VALUES ("First Post","This is the first post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO BLOG_POSTS (TITLE,BODY,DATE_ADDED,DATE_MODIFIED) 
VALUES ("Second Post","This is the second post",CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);