INSERT INTO BLOG_POSTS (ID,TITLE,BODY,DATE_ADDED,DATE_MODIFIED)
VALUES (1,'First Post','This is the first post',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO BLOG_POSTS (ID,TITLE,BODY,DATE_ADDED,DATE_MODIFIED)
VALUES (2,'Second Post','This is the second post',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);